<!doctype html>
<html class="no-js" lang="en" dir="ltr">
<head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><?= $page_title ? $page_title : 'X-Lab'?></title>
    <link rel="stylesheet" href="<?= $this->url->venderUri ?>foundation.min.css">
    <link rel="stylesheet" href="<?= $this->url->venderUri?>foundation-icons.css">
    <link rel="stylesheet" href="<?= $this->url->getStaticBaseUri()?>css/global.css">
    
    <script src="<?= $this->url->venderUri?>jquery-2.2.3.min.js"></script>
	<script src="<?= $this->url->venderUri?>foundation.min.js"></script>
</head>

<body>